feat: add comments for events
agluh/java-explore-with-me pull request #3
Opened 2022-09-23 18:49 UTC by agluh

2022-09-27 18:32 UTC, Ben1t0 requested changes
Хорошая работа, продолжайте! © В целом вопрос только по логике распределения методов по сервисам и в некоторых местах можно NPE схватить

2022-09-27 18:32 UTC, Ben1t0 commented on main/model/src/main/java/ru/practicum/explorewithme/main/model/Comment.java
> +    protected Comment() {
Можно добавить аннотацию @NoArgsConstructor

2022-09-27 18:32 UTC, Ben1t0 commented on main/service-api/src/main/java/ru/practicum/explorewithme/main/service/api/CommentService.java
> +    List<Comment> findCommentsForEvent(long eventId, int from, int size);
Этот метод как будто лучше в EventService перенести

2022-09-27 18:32 UTC, Ben1t0 commented on main/service-api/src/main/java/ru/practicum/explorewithme/main/service/api/EventService.java
> +    void addComment(long eventId, Comment comment);
а зачем 2 метода делать addComent и comentEvent? addComent где-нибудь еще кроме как в comentEvent используется ? Ощущение что весь функционал addComent можно в comentEvent перенести, тем более там уже есть проверка на существование эвента

2022-09-27 18:32 UTC, Ben1t0 commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/CommentMapper.java
> +        return CommentDto.builder()
сюда может прилететь null

2022-09-27 18:32 UTC, Ben1t0 commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
> +                .map(commentMapper::toDto)
здесь тоже можно NPE схватить

2022-09-27 19:12 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
> +                .map(commentMapper::toDto)
Тоже не понял, каким образом это на что-то влияет. Плохо было бы, если нуль пролетает куда то вглубь и хранится какое то время скрыто (например, сеттером), а потом при вызове метода совершенно не относящемуся к делу - оно падает. А в ситуации, где метод просто использует аргумент и упадёт от нуля - ну так не надо вызывать с нулём, это вообще обычная практика в джаве.

2022-09-27 19:12 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/CommentMapper.java
> +        return CommentDto.builder()
Ну и пусть, в чём проблема? Если передать ноль, то оно и не должно работать. Упадёт сразу, всё по правилу fail fast.

2022-09-27 19:14 UTC, agluh commented on main/service-api/src/main/java/ru/practicum/explorewithme/main/service/api/EventService.java
> +    void addComment(long eventId, Comment comment);
addComment - это из-за необходимости сохранять primary сторону one-to-many - это Event, а не Comment. CommentService отвечает за создание комментария, а EventService - за добавление коментария к эвенту. Это немного разные вещи.

2022-09-27 19:14 UTC, agluh commented on main/service-api/src/main/java/ru/practicum/explorewithme/main/service/api/CommentService.java
> +    List<Comment> findCommentsForEvent(long eventId, int from, int size);
Почему? Он касается комментариев, а не эвентов.

2022-09-27 19:20 UTC, agluh commented on main/model/src/main/java/ru/practicum/explorewithme/main/model/Comment.java
> +    protected Comment() {
Да, это можно.

2022-09-27 19:23 UTC, Ben1t0 commented on main/service-api/src/main/java/ru/practicum/explorewithme/main/service/api/CommentService.java
> +    List<Comment> findCommentsForEvent(long eventId, int from, int size);
ну ты вроде как для эвента ищешь все его комментарии, ну мне так логичнее кажется, на самом деле наверное это вкусовщина

2022-09-27 19:26 UTC, Ben1t0 commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/CommentMapper.java
> +        return CommentDto.builder()
так он у тебя 500 ошибку вывалит

2022-09-27 19:28 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/CommentMapper.java
> +        return CommentDto.builder()
Ну и пусть. Значит криво написан код. По хорошему тут null не должен быть, так зачем мне отвечать клиенту 4хх, если это явно проблема сервера?

2022-09-27 19:29 UTC, Ben1t0 commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
> +                .map(commentMapper::toDto)
что именно обычная практика? не вызывать с нулем это хорошо ) всегда бы так везде быть уверенным что никто не вызовет с нулем

2022-09-27 19:31 UTC, Ben1t0 approved these changes

2022-09-27 19:31 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
> +                .map(commentMapper::toDto)
Обычная практика не проверять на нуль, если он не ожидается там и так или иначе выбросит исключение. Ты предлагаешь везде проверять аргументы и кидать IllegalArgumentException? Чем это лучше NPE?

2022-09-27 19:33 UTC, Ben1t0 commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/CommentMapper.java
> +        return CommentDto.builder()
ну можно тогда отловить null в лог записать, код тогда конечно криво написан если null туда прилетает

2022-09-27 19:34 UTC, Ben1t0 commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
> +                .map(commentMapper::toDto)
ну здесь можно было бы просто вместо объекта так же null прокинуть дальше вместо NPE

2022-09-27 19:35 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/CommentMapper.java
> +        return CommentDto.builder()
Ты предлагаешь в маппере логировать нули? Это ж сугубо внутренний класс, утилитный, который вызывается уже когда даже сервисный слой отработал. Чтобы сервис вернул ноль - это что-то крайне странное. Такие случаи скорее там логироваться и будут.

2022-09-27 19:41 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
> +                .map(commentMapper::toDto)
Интереса ради - нашёл это фрагмент у тебя. Ну вот прокинул ты null дальше в дто и в этой строчке получил NPE. Толку то от этого тогда?
https://github.com/Ben1t0/java-explore-with-me/blob/2ec304d120416e7072832a95da09f441290c9b4d/ewm-service/src/main/java/ru/practicum/explore_with_me/service/event/EventServiceImpl.java#L58

2022-09-27 19:43 UTC, agluh commented on main/service-api/src/main/java/ru/practicum/explorewithme/main/service/api/CommentService.java
> +    List<Comment> findCommentsForEvent(long eventId, int from, int size);
Я обычно смотрю на сущность, которая возвращается. Тут возвращаются комменты, значит это сервис комментариев, так решил.

2022-09-27 19:45 UTC, Ben1t0 commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
> +                .map(commentMapper::toDto)
это да, там я уже проверку не сделал мой косяк , а так как ты и сказал выше что это утилитный класс и он как раз вернет null и потом уже можно разбираться с этими null особенно когда stream бежит по всей коллекции из-за NPE  у тебя вся обработка потока упадет 
ладно эта дискуссия про nullы затянулась )

2022-09-27 19:49 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
> +                .map(commentMapper::toDto)
Ну, мне просто интересно стало, почему ты думаешь, что в коллекции будут нули. Это как раз вроде попахивает, чтобы там нули были. А если их нет, зачем в маппере проверять. Так можно и в контроллере проверять начать, что там маппер не ноль вернул. Имхо это запутывает и уводит от источника ошибки.

2022-09-29 09:43 UTC, uPagge commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +      <column name="comment" type="text">
Лучше, если поле не будет совпадать с название таблицы, уж больно похожи названия comments и comment

Можно использовать например message

2022-09-29 09:43 UTC, uPagge commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +        <constraints nullable="false" foreignKeyName="fk_comments_author_id"
Для полей, которые используются в таких соединениях, можно создавать индексы. Довольно универсальный совет, который ускоряет запросы в 90% случаях

2022-09-29 09:43 UTC, uPagge commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +      <column name="event_id" type="bigint">
Комментарии обычно общие на всю систему, поэтому лучше использовать связующую таблицу. Потом появится еще какая-нибудь сущность, для которой нужны комментарии. В данном случае придется добавить еще одно поле.

2022-09-29 09:43 UTC, uPagge commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +        <constraints nullable="false" foreignKeyName="fk_comments_event_id"
Можно еще добавить deleteCascade="true". Если событие удаляется, то и комментарии тоже можно удалять.

2022-09-29 09:43 UTC, uPagge commented on main/service-api/src/main/java/ru/practicum/explorewithme/main/service/api/CommentService.java
> +    List<Comment> findCommentsForEvent(long eventId, int from, int size);
Обычно фронту нужна также информаци о том, на какой пользователь странице, сколько всего страниц, сколько всего элементов. Поэтому лучше использовать пагинацию спринга, класс Page<>.

2022-09-29 09:43 UTC, uPagge commented on main/service-impl/src/main/java/ru/practicum/explorewithme/main/service/impl/CommentServiceImpl.java
> +        }
Лучше эту проверку перенести до получения participants, если она не проходит, то и получать participants нам не нужно

2022-09-29 09:43 UTC, uPagge commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
>              .withCreatedOn(event.getCreatedOn())
А зачем везде добавлено with? 😅

2022-09-29 09:43 UTC, uPagge commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/pub/UserController.java
> +    public void addComment(
Стано, что этот эндпойнт находится в UserController

2022-09-29 09:55 UTC, agluh commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +      <column name="comment" type="text">
Да, тоже иногда путался. Возьму на заметку 👍

2022-09-29 09:55 UTC, agluh commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +        <constraints nullable="false" foreignKeyName="fk_comments_author_id"
До последнего держал в голове проблему индексов и всё откладывал на последок. Ну и забыл в итоге) Спасибо за совет, попробую прикрутить.

2022-09-29 10:01 UTC, agluh commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +      <column name="event_id" type="bigint">
Эмм. Тогда не понятно, как связать это в ORM. Сейчас там стоит на стороне эвента
```java
@OneToMany(
   cascade = CascadeType.ALL,
   orphanRemoval = true,
   mappedBy = "event" // <--- это как раз поле в комментарии event_id
)
```
С many-to-many пока не придумывается решение.

2022-09-29 10:01 UTC, agluh commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +        <constraints nullable="false" foreignKeyName="fk_comments_event_id"
Хорошо, добавлю.

2022-09-29 10:03 UTC, agluh commented on main/service-impl/src/main/java/ru/practicum/explorewithme/main/service/impl/CommentServiceImpl.java
> +        }
Резонно, сделаю.

2022-09-29 10:04 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/common/mapping/EventMapper.java
>              .withCreatedOn(event.getCreatedOn())
А мне нравится, чтобы было понятно с какими полями мы собираем билдер) Обычно этот паттерн вроде с таким префиксом везде упоминается, у меня и прижился тоже.

2022-09-29 10:05 UTC, agluh commented on main/web/src/main/java/ru/practicum/explorewithme/main/web/pub/UserController.java
> +    public void addComment(
Ну, это же юзер типа добавляет комментарии - у нас нету авторизации и откуда-то я должен взять автора комментария. Автор есть только по пути с /user/{id}/...

2022-09-29 10:08 UTC, agluh commented on main/service-api/src/main/java/ru/practicum/explorewithme/main/service/api/CommentService.java
> +    List<Comment> findCommentsForEvent(long eventId, int from, int size);
На самом деле этот метод нигде не вызывается - комментарии встраиваются в сам эвент (считаем, что их не много 😊) и метод можно допнуть. Нет метода - нет проблем ))

2022-09-29 12:05 UTC, uPagge commented on main/app/src/main/resources/db/changelog/1.0.0/add-comments.xml
> +      <column name="event_id" type="bigint">
В ORM это будет ManyToOne, вам должны были прочитать лекцию про это. На стороне БД будет выглядеть, как many-to-many

2022-10-09 15:26 UTC, merged